version: '3.7'

services:
  studybuddy:
    image: bishnudev/study-buddy:production
    ports:
      - 80:4000
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  uploads: