version: '3.7'

services:
  backend:
    image: backend
    build: ./back-end
    ports:
      - "4000:4000"
    env_file:
      - ./back-end/.env
  frontend:
    image: frontend
    build: ./front-end
    ports:
      - "3000:3000"
    env_file:
      - ./front-end/.env