name: Deploy To Production Server

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  deploy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/study-buddy:production
          build-args: |
            REACT_APP_BACK_URL=${{ secrets.PROD_REACT_APP_BACK_URL }}
            REACT_APP_WEBSOCKET_URL=${{ secrets.PROD_REACT_APP_WEBSOCKET_URL }}